# Generated by Django 5.0.1 on 2024-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients image')),
                ('name', models.CharField(default='Some default client name', max_length=35)),
                ('opinion', models.CharField(default='Some default opinion', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Some full name', max_length=50)),
                ('email', models.EmailField(default='email', max_length=50)),
                ('phone', models.CharField(default='phone', max_length=20)),
                ('message', models.CharField(default='Message', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Guards image')),
                ('name', models.CharField(default='Guard name', max_length=30)),
                ('status', models.CharField(default='Guard status', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services')),
                ('title', models.CharField(default='Default title', max_length=40)),
                ('body', models.CharField(default='Some default text', max_length=255)),
            ],
        ),
    ]
