# Generated by Django 5.0.1 on 2024-01-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='obunalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='opinion',
            field=models.TextField(default='Some default opinion', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='Message', max_length=255),
        ),
    ]
