# Generated by Django 5.0.1 on 2024-01-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_obunalar_alter_client_opinion_alter_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obunalar',
            old_name='email',
            new_name='email_sub',
        ),
    ]
